# Macro file for the initialization
# in interactive session
#
# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#

# Add your collimator control command here
/mydetector/includeCollimator false

# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute ./macros/vis.mac
